### ISSUE TITLE
Invisible Units

### ISSUE THREAD

**Issue by SchoeniosX** [the-s-is-silent/Outlaws-of-the-Wastes#14]
Some of the unmodified profile pictures on some units are invisible and may not have been pixelated yet.

![Screenshot_20231225-091713_Unciv](https://github.com/the-s-is-silent/Outlaws-of-the-Wastes/assets/148587231/6432f5ed-c3f1-4e46-8075-ed6688e0628a)

**Comment by the-s-is-silent** [comment]
You have encountered units that don't yet have sprite art. Due to my own art skills being nonexistent, I've had to borrow sprites used for DeCiv for most of the units that don't replace other units, and even then, there's a handful of units in the mod that this really doesn't work for and I'm hesitant to request the aid of someone on the Unciv or DeCiv servers who is a sprite maker. (Also, my current laptop is a "potato" quality Chromebook which is incapable of generating atlas files when it runs Unciv and doesn't have the necessary RAM to install the programs needed to do so, so when the sprites/icons are added I do have to ask someone else to do that step for me.)
